const ADD_PRODUCT = "ADD_PRODUCT"
const FETCH_PRODUCTS = "FETCH_PRODUCTS"
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"
const DELETE_PRODUCT = "DELETE_PRODUCT"

export default {
    ADD_PRODUCT,
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAILED,
    DELETE_PRODUCT
}
