const CREATE_ORDER = "CREATE_ORDER"
const FETCH_ORDER_LOADING = "FETCH_ORDER_LOADING"
const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED"

export default {
    CREATE_ORDER,
    FETCH_ORDER_LOADING,
    FETCH_ORDER_SUCCESS,
    FETCH_ORDER_FAILED 
}
