const ADD_TO_BASKET = "ADD_TO_BASKET"
const DELETE_FROM_BASKET = "DELETE_FROM_BASKET"
const CHANGE_QUANTITY_PLUS = "CHANGE_QUANTITY_PLUS"
const CHANGE_QUANTITY_MINUS = "CHANGE_QUANTITY_MINUS"

export default {
    ADD_TO_BASKET,
    DELETE_FROM_BASKET,
    CHANGE_QUANTITY_PLUS ,
    CHANGE_QUANTITY_MINUS 
}
