const PRODUCT_FETCH = "PRODUCT_FETCH";
const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
const PRODUCT_FAILED = "PRODUCT_FAILED";
const PRODUCT_UPDATE = "PRODUCT_UPDATE";

export default {
  PRODUCT_FETCH,
  PRODUCT_SUCCESS,
  PRODUCT_FAILED,
  PRODUCT_UPDATE,
};
